apiVersion: v1
kind: Service
metadata:
  name: planner-service
  namespace: aegis-aml
spec:
  type: ClusterIP
  selector:
    app: planner-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
