apiVersion: v1
kind: Service
metadata:
  name: evidence-service
  namespace: aegis-aml
spec:
  type: ClusterIP
  selector:
    app: evidence-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
