"use client"

import { useEffect, useState, useMemo } from "react"
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from "recharts"
import { Download, FileText, BrainCircuit, TrendingUp, CheckCircle2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { allocateTeams } from "@/lib/optimizer"
import { priorityFromRre } from "@/lib/utils"

interface RreRow { segment_id: string; total_violations: number; active_days: number; capacity_loss: number; rre_score: number; road_name: string; highway_class: string; zone_id: string; priority: string; core_parking_violations?: number; avg_severity?: number; persistence?: number; junction_penalty?: number; demand_multiplier?: number }

export default function DeployPage() {
  const [data, setData] = useState<RreRow[]>([])
  const [numTeams, setNumTeams] = useState(5)
  const [shiftHours, setShiftHours] = useState(4)
  const [brief, setBrief] = useState("")
  const [briefing, setBriefing] = useState(false)

  useEffect(() => {
    fetch("/api/data?type=top-roads")
      .then((r) => r.json())
      .then((d: Record<string, unknown>[]) => setData(
        d.map((r, i) => ({
          segment_id: r.segment_id as string,
          total_violations: r.total_violations as number,
          active_days: r.active_days as number,
          capacity_loss: r.capacity_loss as number,
          rre_score: r.rre_score as number,
          road_name: r.road_name as string,
          highway_class: r.highway_class as string,
          zone_id: `ZONE-${String(i + 1).padStart(3, "0")}`,
          priority: priorityFromRre(r.rre_score as number),
        }))
      ))
  }, [])

  const displayData = useMemo(() => {
    const alloc = allocateTeams(data, numTeams, shiftHours)
    const seen = new Set<string>()
    return alloc.filter((r) => { const k = `${r.Zone}-${r.priority}`; if (seen.has(k)) return false; seen.add(k); return true })
  }, [data, numTeams, shiftHours])

  const csvContent = useMemo(() => {
    if (!displayData.length) return ""
    return [Object.keys(displayData[0]).join(","), ...displayData.map((r) => Object.values(r).join(","))].join("\n")
  }, [displayData])

  const jsonContent = useMemo(() => JSON.stringify(displayData, null, 2), [displayData])

  const htmlContent = useMemo(() => {
    const headers = Object.keys(displayData[0] || {}).join("</th><th>")
    const rows = displayData.map((r) => `<tr><td>${Object.values(r).map((v) => typeof v === "number" ? v.toFixed(2) : v).join("</td><td>")}</td></tr>`).join("\n")
    return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{font-family:Inter,sans-serif;padding:40px;background:#F7F4EF}table{border-collapse:collapse;width:100%;background:white;border-radius:12px;overflow:hidden}th,td{padding:10px 14px;text-align:left;border-bottom:1px solid #eee}th{background:#050505;color:#F7F4EF;font-size:11px;text-transform:uppercase;letter-spacing:0.5px}h2{color:#050505;font-weight:700}.meta{color:#666;font-size:13px}.footer{margin-top:20px;color:#999;font-size:11px}</style></head><body><h2>TRINETRA Daily Dispatch Brief</h2><p class="meta">${new Date().toISOString().slice(0,10)} · ${numTeams} Teams · ${shiftHours}h Shifts</p><table><tr><th>${headers}</th></tr>${rows}</table><p class="footer">Generated by TRINETRA Command Intelligence · BTP GridLock 2.0</p></body></html>`
  }, [displayData, numTeams, shiftHours])

  const generateBrief = () => {
    setBriefing(true)
    setBrief("")
    const teams = [...new Set(displayData.map((r) => r.Team))].length
    const zones = [...new Set(displayData.map((r) => r.Zone))].length
    const critical = displayData.filter((r) => r.priority === "Critical").length
    const high = displayData.filter((r) => r.priority === "High").length
    const totalRecovery = displayData.reduce((s, r) => s + r["Expected Recovery"], 0)
    const text =
`TRINETRA DAILY ENFORCEMENT BRIEF
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Date: ${new Date().toISOString().slice(0, 10)}
Shift: ${shiftHours}h · Teams Deployed: ${teams}

EXECUTIVE SUMMARY
Today's dispatch plan covers ${zones} enforcement zones across Bengaluru.
Priority breakdown:
  • Critical: ${critical} zones
  • High: ${high} zones
  • Other: ${zones - critical - high} zones

Expected capacity recovery: ${totalRecovery.toFixed(1)} RRE units

OPERATIONAL DIRECTIVES
• Tow Units should prioritize Critical sectors exhibiting high persistence
  and above-median capacity loss proxies
• Exercise discretion on low-confidence zones (fewer than 30 recorded violations)
• Enforce "Tow + repeat patrol" strategy in Q1 obvious hotspots
• Field validation required for all new watch segments

CLOSED-LOOP FEEDBACK
All dispatched units must submit post-patrol reports:
  - Obstruction present/absent
  - Action taken (tow/challan/warning)
  - Vehicles towed count
  - Recurrence assessment after 7 days

This feedback recalibrates RRE confidence and persistence weights.`
    let i = 0
    const iv = setInterval(() => {
      setBrief(text.slice(0, i))
      i++
      if (i > text.length) { clearInterval(iv); setBriefing(false) }
    }, 8)
  }

  const priorityDist = useMemo(() => {
    const c: Record<string, number> = {}
    displayData.forEach((r) => { c[r.priority] = (c[r.priority] || 0) + 1 })
    return Object.entries(c).map(([name, value]) => ({ name, value }))
  }, [displayData])

  return (
    <div className="space-y-8">
      <div>
        <h1 className="font-display text-4xl font-bold tracking-tighter text-deep-black">Deployment & Export</h1>
        <p className="text-text-secondary mt-2">Dispatch planning, exportable enforcement briefs, and closed-loop learning</p>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="bg-white rounded-2xl p-5 border border-border-subtle shadow-soft">
          <p className="text-[9px] font-bold uppercase tracking-widest text-text-secondary mb-3">Tow / Patrol Teams</p>
          <input type="range" min={1} max={15} value={numTeams} onChange={(e) => setNumTeams(Number(e.target.value))} className="w-full accent-electric-mint" />
          <span className="font-display text-2xl font-bold mt-1 block">{numTeams}</span>
        </div>
        <div className="bg-white rounded-2xl p-5 border border-border-subtle shadow-soft">
          <p className="text-[9px] font-bold uppercase tracking-widest text-text-secondary mb-3">Shift Duration</p>
          <input type="range" min={2} max={8} value={shiftHours} onChange={(e) => setShiftHours(Number(e.target.value))} className="w-full accent-electric-mint" />
          <span className="font-display text-2xl font-bold mt-1 block">{shiftHours}h</span>
        </div>
      </div>

      <div className="bg-white rounded-3xl border border-border-subtle shadow-soft overflow-hidden">
        <div className="p-6 border-b border-border-subtle flex items-center justify-between">
          <div>
            <h3 className="font-display text-lg font-bold">Dispatch Roster</h3>
            <p className="text-xs text-text-secondary">{displayData.length} assignments · {numTeams} units</p>
          </div>
          {priorityDist.length > 0 && (
            <ResponsiveContainer width={200} height={40}>
              <BarChart data={priorityDist} layout="vertical">
                <Bar dataKey="value" radius={[0, 4, 4, 0]}>
                  {priorityDist.map((_, i) => <Cell key={i} fill={i === 0 ? "#FF6B73" : i === 1 ? "#F6E85D" : "#18D68B"} />)}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          )}
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-warm-cream/50">
                {displayData.length > 0 && Object.keys(displayData[0]).map((h) => (
                  <th key={h} className="text-left py-3 px-4 text-[9px] font-bold uppercase tracking-widest text-text-secondary">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {displayData.map((r, i) => (
                <tr key={i} className="border-b border-border-subtle/30 hover:bg-warm-cream transition-colors">
                  {Object.values(r).map((v, j) => (
                    <td key={j} className="py-3 px-4">{typeof v === "number" ? v.toFixed(2) : String(v)}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-4">
        <a href={`data:text/csv;charset=utf-8,${encodeURIComponent(csvContent)}`} download="trinetra-dispatch.csv" className="block">
          <Button variant="secondary" size="lg" className="w-full"><Download size={16} /> Download CSV</Button>
        </a>
        <a href={`data:application/json;charset=utf-8,${encodeURIComponent(jsonContent)}`} download="trinetra-dispatch.json" className="block">
          <Button variant="secondary" size="lg" className="w-full"><Download size={16} /> Download JSON</Button>
        </a>
        <a href={`data:text/html;charset=utf-8,${encodeURIComponent(htmlContent)}`} download="trinetra-dispatch-brief.html" className="block">
          <Button variant="secondary" size="lg" className="w-full"><Download size={16} /> HTML Brief</Button>
        </a>
      </div>

      <div className="bg-charcoal text-white rounded-3xl p-6 border border-white/10">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2">
            <BrainCircuit size={18} className="text-electric-mint" />
            <h3 className="font-display text-lg font-bold">AI Operational Brief</h3>
          </div>
          <button onClick={generateBrief} disabled={briefing}
            className="px-5 py-2.5 rounded-full bg-electric-mint text-deep-black text-xs font-bold hover:scale-105 transition-transform disabled:opacity-50 flex items-center gap-1.5">
            <FileText size={12} />
            Generate Brief
          </button>
        </div>
        {brief ? (
          <div className="bg-white/5 rounded-2xl p-6 border border-white/10">
            <pre className="text-sm whitespace-pre-wrap font-sans leading-relaxed text-white/80">{brief}</pre>
          </div>
        ) : (
          <div className="flex items-center justify-center py-8 text-white/30 text-sm">Click "Generate Brief" for AI-powered shift briefing</div>
        )}
      </div>

      <div className="bg-white rounded-3xl p-6 border border-border-subtle shadow-soft">
        <div className="flex items-center gap-2 mb-6">
          <TrendingUp size={18} className="text-electric-mint" />
          <h3 className="font-display text-lg font-bold">Closed-Loop Learning</h3>
        </div>
        <div className="grid grid-cols-3 gap-4 mb-6">
          {[
            { label: "Recommendation Precision", value: "89.2%", trend: "+2.1%", up: true },
            { label: "Field Validation Rate", value: "94.5%", trend: "-0.4%", up: false },
            { label: "Recurrence Reduction", value: "41.2%", trend: "+5.3%", up: true },
          ].map((m) => (
            <div key={m.label} className="bg-warm-cream rounded-2xl p-4">
              <p className="text-[9px] font-bold uppercase tracking-widest text-text-secondary">{m.label}</p>
              <p className="font-display text-3xl font-bold mt-1">{m.value}</p>
              <p className={`text-xs font-bold mt-1 flex items-center gap-1 ${m.up ? "text-electric-mint" : "text-coral-pink"}`}>
                {m.up ? <TrendingUp size={12} /> : <TrendingUp size={12} className="rotate-180" />}
                {m.trend}
              </p>
            </div>
          ))}
        </div>
        <p className="text-xs text-text-secondary border-t border-border-subtle pt-4">
          In production, each dispatched zone receives officer feedback (obstruction present, action taken, vehicles towed, 7-day recurrence) to recalibrate RRE confidence and persistence weights.
        </p>
      </div>
    </div>
  )
}
